In [1]:
## Instalar Numpy

% pip install numpy

UsageError: Line magic function `%` not found.


In [2]:
import numpy as np ## as np: importamos la libreria con ese alias, para llamarla en el codigo ponemos 'np'

### COMO CREAR UN ARREGLO O ARRAY ###

my_list = [0,1,2,3,4]
my_array = np.array(my_list) # me transforma en array mi lista

In [3]:
print(type(my_list))
print(type(my_array))

<class 'list'>
<class 'numpy.ndarray'>


In [5]:
np.arange(start=2 ,stop=10, step=2) # el limite superior no lo incluye, atento a eso
# es igual a un range solo que la devolucion es en forma de array, lo que favorece
# si manipulacion posterior.
# seria una forma facil de resolver el ejercicio de Lista de divisibles
# nos ahorrariamos un paso que seria el de transformar en lista, aqui transformariamos en array


array([2, 4, 6, 8])

In [13]:
np.linspace(start = 11 ,stop = 12, num = 7) 
# toma pasos iguales para llegar hasta stop, especificando la cantidad de pasos (7)

array([11.        , 11.16666667, 11.33333333, 11.5       , 11.66666667,
       11.83333333, 12.        ])

In [7]:
# Arreglos vacios(ceros) predefinidos:
array_vacio = np.zeros(4)
print(array_vacio)

type(array_vacio[1])

[0. 0. 0. 0.]


numpy.float64

In [15]:
# Arreglos predefinidos: array rellenado con unos
array_unos = np.ones(4)
print(array_unos)

type(array_unos[0])

[1. 1. 1. 1.]


numpy.float64

In [19]:
# Crear matriz array
my_matrix = np.full(shape=(2,3),fill_value=5) #crea una matriz 2x2 con todos sus valores 5
# fill_value = valor de llenado

# PRIMER VALOR: cantidad de filas de nuestra matriz
# SEGUNDO VALOR: cantidad de columnas de nuestra matriz

print (my_matrix)

[[5 5 5]
 [5 5 5]]


In [18]:
base = np.linspace(2,4,6)
base

# Primer elemento: start, tambien se puede escribir: start=2
# Segundo elemento: stop, tambien se puede escribir: stop=4
# Tercer elemento: step, tambien se puede escribir: step=6

array([2. , 2.4, 2.8, 3.2, 3.6, 4. ])

In [20]:
pi = np.pi # devuelve el numero pi
print (pi, type(pi)) # lo devuelve como un float, no como un numpy.float

3.141592653589793 <class 'float'>


In [ ]:
my_array = np.full_like(base, np.pi)
my_array

# Retorna un array completado, con la misma estructura
# y tipo de dato del array dado.

<h1>Crear arrays aleatorios</h1>


In [10]:
np.random.ran(2,2)


TypeError: 'module' object is not callable

In [ ]:
np.random.uniform(low=0 , high=1, size=6)

#distribucion normal: 

<h1>Tamaño de los arrays<h1> 

In [23]:
a=np.arange(1,10)
print(a)

[1 2 3 4 5 6 7 8 9]


In [26]:
b=np.reshape(a,[3,3])
print(b)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [27]:
print(b.dtype)

int32


<h1>Manipulando arrays<h1>

In [ ]:
matriz=np.arange(3)

In [ ]:
print(matriz[1,2]) # el primero me indica la fila y el segundo la columna

In [ ]:
#obtener todos los elementos de la fila 0

print(matriz[0,:])

In [ ]:
#obtener todos los elementos de la columna 1

print(matriz[:,1])

In [ ]:
#obtener el primer y segundo elemento de las columnas 1 y 2

print(matriz[0:2 , 0:2])

In [ ]:
## obtener todo
print(matriz[:,:])

<h1>Copiar Arrays<h1>

In [30]:
a= np.array([2,4,6])
a

array([2, 4, 6])

In [31]:
b= a.copy()
print(b)

[2 4 6]


In [35]:
a[1]=8
print (a)
print (b)


[2 8 6]
[2 4 6]
