In [1]:
## Instalar numpy
%pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [3]:
import numpy as np

In [4]:
my_list = [0,1,2,3,4]

my_array = np.array(my_list)

In [6]:
print(type(my_array))

<class 'numpy.ndarray'>


In [7]:
type(my_list)

list

In [8]:
np.arange(start=2, stop=10, step=2)

array([2, 4, 6, 8])

In [9]:
np.linspace(start= 11, stop = 12, num=7)

array([11.        , 11.16666667, 11.33333333, 11.5       , 11.66666667,
       11.83333333, 12.        ])

In [10]:
## Arreglos vacios predefinidos
print(np.zeros(4))

[0. 0. 0. 0.]


In [11]:
print(np.ones(4))

[1. 1. 1. 1.]


In [12]:
np.full(shape=(2,2), fill_value=5)

array([[5, 5],
       [5, 5]])

In [13]:
base = np.linspace(2,4,6)
base

array([2. , 2.4, 2.8, 3.2, 3.6, 4. ])

In [14]:
np.pi

3.141592653589793

In [15]:
my_array = np.full_like(base, np.pi)
my_array

array([3.14159265, 3.14159265, 3.14159265, 3.14159265, 3.14159265,
       3.14159265])

## Crear arrays aleatorios

In [16]:
np.random.rand(2,2)

array([[0.21550557, 0.43509035],
       [0.72110192, 0.00075433]])

In [17]:
np.random.uniform(low=0, high=1, size=6)

array([0.72761291, 0.83562484, 0.56867164, 0.81463593, 0.41866934,
       0.09128496])

In [18]:
np.random.randn(2,2)

array([[-0.11401326, -1.86822565],
       [ 1.44931947,  0.60261788]])

In [19]:
np.random.normal(loc=0, scale=2, size=6)

array([ 2.09507907, -3.59920264, -0.77676143,  1.85333559,  1.65252444,
        2.12419958])

## Tamaño de los arrays

In [20]:
a = np.arange(1,10)
print(a)

[1 2 3 4 5 6 7 8 9]


In [22]:
b = np.reshape(a, [3,3])
print(b)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [24]:
print(b.dtype)

int32


In [25]:
c = b.flatten()
c

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

## Manipulando arrays

In [28]:
matriz = np.arange(9).reshape(3,3)
matriz

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [29]:
## entramos en la fila 1 y columna 2

print(matriz[1 , 2])

5


In [30]:
## obtener todos los elementos de la fila 0

print(matriz[0 , :])

[0 1 2]


In [31]:
## obtener todos los elementos de la columna 1

print(matriz[ : , 1])

[1 4 7]


In [32]:
# obtener el primer y segundo elemento de las columnas 1 y 2

print(matriz[0:2 , 0:2])


[[0 1]
 [3 4]]


In [33]:
## obtener todo
print(matriz[:, :])

[[0 1 2]
 [3 4 5]
 [6 7 8]]


## Copiar arrays

In [34]:
a = np.array([2,4,6])
a

array([2, 4, 6])

In [35]:
b = a.copy()
print(b)

[2 4 6]


In [36]:
a[1] = 8
print(a)

[2 8 6]


In [37]:
print(b)

[2 4 6]


In [38]:
a1 =  np.array([2,4,6])
a1

array([2, 4, 6])

In [39]:
b1 = a1
print(b1)

[2 4 6]


In [40]:
a1[1] = 8
print(a1)

[2 8 6]


In [41]:
print(b1)

[2 8 6]


## Operaciones con arrays

### Suma

In [42]:
a = np.arange(5,11)
a

array([ 5,  6,  7,  8,  9, 10])

In [43]:
print(a+10)

[15 16 17 18 19 20]


### Resta

In [44]:
print(a-10)

[-5 -4 -3 -2 -1  0]


In [45]:
b = np.full(4,3)
c = np.ones(4, dtype='int')

In [46]:
print(b)

[3 3 3 3]


In [47]:
print(c)

[1 1 1 1]


In [48]:
print(b-c)

[2 2 2 2]


## Multiplicacion

In [49]:
a = np.array([[2,3], [2,3], [2,3]])
a.shape

(3, 2)

In [50]:
b = np.array([[1,6,5,2,7],[1,2,7,0,9]])
b.shape

(2, 5)

In [51]:
np.matmul(a,b)

array([[ 5, 18, 31,  4, 41],
       [ 5, 18, 31,  4, 41],
       [ 5, 18, 31,  4, 41]])

In [53]:
a

array([[2, 3],
       [2, 3],
       [2, 3]])

In [54]:
b

array([[1, 6, 5, 2, 7],
       [1, 2, 7, 0, 9]])

In [55]:
c = a@b
c

array([[ 5, 18, 31,  4, 41],
       [ 5, 18, 31,  4, 41],
       [ 5, 18, 31,  4, 41]])

In [56]:
c.T

array([[ 5,  5,  5],
       [18, 18, 18],
       [31, 31, 31],
       [ 4,  4,  4],
       [41, 41, 41]])

## Estadistica

In [57]:
lista = [74, 74, 72, 72, 73, 69, 69, 71, 76, 71, 73, 73, 74, 74, 69, 70, 73, 75, 78, 79, 76, 74, 76, 72, 71, 75]


In [66]:
lista.sort()

In [65]:
print(lista)

[69, 69, 69, 70, 71, 71, 71, 72, 72, 72, 73, 73, 73, 73, 74, 74, 74, 74, 74, 75, 75, 76, 76, 76, 78, 79]


In [58]:
np.mean(lista)

73.1923076923077

In [59]:
np.median(lista)

73.0

In [60]:
np.std(lista)

2.572326554954764

In [61]:
np.max(lista)

79

In [67]:
np.min(lista)

69

## Mascaras

In [68]:
a = np.arange(0,20).reshape(2,10)
print(a)

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]]


In [69]:
mascara = ((a % 2) == 0)
print(mascara)

[[ True False  True False  True False  True False  True False]
 [ True False  True False  True False  True False  True False]]


In [70]:
a[mascara]

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])